# scene
scene: igibson
scene_id: Beechwood_1_int #Merom_0_int
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 2
should_open_all_doors: false
# load_object_categories: ["armchair", "window"]
not_load_object_categories: ["door",'ceilings']
# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot:
  name: Fetch
  action_type: continuous
  action_normalize: true
  base_name: null
  scale: 0.8
  self_collision: true
  rendering_params: null
  grasping_mode: physical
  rigid_trunk: true
  reset_joint_pos: tuck
  default_trunk_offset: 0.365
  default_arm_pose: horizontal
  controller_config:
    base:
      name: DifferentialDriveController
    arm_0:
      name: InverseKinematicsController
      kv: 2.0
    gripper_0:
      name: MultiFingerGripperController
      mode: binary
    camera:
      name: JointController
      use_delta_commands: False

# reward
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.1

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# sensor spec
output: [task_obs, rgb, depth, scan, seg, occupancy_grid]
# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 640
image_height: 480
vertical_fov: 45
# depth
depth_low: 0.8
depth_high: 3.5
# scan
# Hokuyo URG-04LX-UG01
# https://www.hokuyo-aut.jp/search/single.php?serial=166
# n_horizontal_rays is originally 683, sub-sampled 1/3
n_horizontal_rays: 228
n_vertical_beams: 1
laser_linear_range: 3.5
laser_angular_range: 240.0
min_laser_dist: 0.05
laser_link_name: laser_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visible_target: true
visible_path: false
